import { useState, useCallback } from "react";
import "./styles/Work.css";
import WorkImage from "./WorkImage";
import { MdArrowBack, MdArrowForward } from "react-icons/md";

const projects = [
  { title: "Zoddspace", category: "Web3 Community & Experiments", tools: "React, TypeScript, Web3, motion design", image: "/images/callhq.png", link: "https://t.me/zoddspace" },
  { title: "3D Portfolio", category: "Immersive Developer Experience", tools: "Three.js, React Three Fiber, GSAP", image: "/images/whatsapp.png", link: "https://github.com/heiszodd/3d-portfolio" },
  { title: "On-chain Interfaces", category: "Product Design & Engineering", tools: "Full-stack systems, APIs, wallet flows", image: "/images/broki.png", link: "https://github.com/heiszodd" },
  { title: "Creative Systems", category: "Interactive Web Experiences", tools: "React, animation, rapid prototyping", image: "/images/orrdr.png", link: "https://github.com/heiszodd" },
];
const Work = () => { const [currentIndex,setCurrentIndex]=useState(0); const [isAnimating,setIsAnimating]=useState(false); const goToSlide=useCallback((index:number)=>{if(isAnimating)return;setIsAnimating(true);setCurrentIndex(index);setTimeout(()=>setIsAnimating(false),500)},[isAnimating]); const prev=()=>goToSlide(currentIndex===0?projects.length-1:currentIndex-1); const next=()=>goToSlide(currentIndex===projects.length-1?0:currentIndex+1); return <div className="work-section" id="work"><div className="work-container section-container"><h2>Selected <span>Work</span></h2><div className="carousel-wrapper"><button className="carousel-arrow carousel-arrow-left" onClick={prev} aria-label="Previous project" data-cursor="disable"><MdArrowBack /></button><button className="carousel-arrow carousel-arrow-right" onClick={next} aria-label="Next project" data-cursor="disable"><MdArrowForward /></button><div className="carousel-track-container"><div className="carousel-track" style={{transform:`translateX(-${currentIndex*100}%)`}}>{projects.map((project,index)=><div className="carousel-slide" key={index}><div className="carousel-content"><div className="carousel-info"><div className="carousel-number"><h3>0{index+1}</h3></div><div className="carousel-details"><h4>{project.title}</h4><p className="carousel-category">{project.category}</p><div className="carousel-tools"><span className="tools-label">Stack & Focus</span><p>{project.tools}</p></div></div></div><div className="carousel-image-wrapper"><WorkImage image={project.image} alt={project.title} link={project.link}/></div></div></div>)}</div></div><div className="carousel-dots">{projects.map((_,index)=><button key={index} className={`carousel-dot ${index===currentIndex?"carousel-dot-active":""}`} onClick={()=>goToSlide(index)} aria-label={`Go to project ${index+1}`} data-cursor="disable" />)}</div></div></div></div>;
};
export default Work;
